permalink: /blog/:title
sakura-jekyll-version: 0.9.0
# Information required for feed
title: MiteshNinja # Change this to your site name.
description: The master of shadows.
url:
author:
    twitter: # twitter user name here

date_format: "%b %d, %Y"

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "" # Set this to default author


# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname:
twitter:
    username: miteshninja

# Includes an icon in the 'ABOUT' page for each username you enter
footer-links:
  dribbble:
  email: mitesh@miteshshah.com
  facebook: miteshninja
  flickr: miteshninja
  github: miteshninja
  instagram: miteshninja
  linkedin: mitesh-shah
  pinterest:
  rss: True # just type anything here for a working RSS icon
  twitter: miteshninja
  stackoverflow: users/4395646/miteshninja # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

gems:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
